//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchKid.Data.Query.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChurchKid.Data.Query.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///CountryId,
        ///Name,
        ///DateCreated,
        ///CreatedById,
        ///LastModified
        ///FROM
        ///countries.
        /// </summary>
        internal static string SqlGetAllCountries {
            get {
                return ResourceManager.GetString("SqlGetAllCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///islands.IslandId,
        ///islands.CountryId,
        ///islands.Name,
        ///islands.DateCreated,
        ///islands.CreatedById,
        ///islands.LastModified
        ///FROM
        ///islands
        ///INNER JOIN countries ON islands.CountryId = countries.CountryId.
        /// </summary>
        internal static string SqlGetAllIslands {
            get {
                return ResourceManager.GetString("SqlGetAllIslands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///localities.LocalityId,
        ///localities.RegionId,
        ///localities.LocalityGroupId,
        ///localities.`Name`,
        ///localities.Description,
        ///localities.DateCreated,
        ///localities.CreatedById,
        ///localities.LastModified
        ///FROM
        ///localities
        ///INNER JOIN regions ON localities.RegionId = regions.RegionId
        ///LEFT OUTER JOIN localitygroups ON localities.LocalityGroupId = localitygroups.LocalityGroupId
        ///LEFT OUTER JOIN islands ON regions.IslandId = islands.IslandId
        ///INNER JOIN countries ON regions.CountryId = countries.CountryId.
        /// </summary>
        internal static string SqlGetAllLocalities {
            get {
                return ResourceManager.GetString("SqlGetAllLocalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///localitygroups.LocalityGroupId,
        ///localitygroups.RegionId,
        ///localitygroups.Name,
        ///localitygroups.`Description`,
        ///localitygroups.DateCreated,
        ///localitygroups.CreatedById,
        ///localitygroups.LastModified
        ///FROM
        ///localitygroups
        ///INNER JOIN regions ON localitygroups.RegionId = regions.RegionId
        ///INNER JOIN countries ON regions.CountryId = countries.CountryId
        ///LEFT OUTER JOIN islands ON regions.IslandId = islands.IslandId.
        /// </summary>
        internal static string SqlGetAllLocalityGroups {
            get {
                return ResourceManager.GetString("SqlGetAllLocalityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///regions.RegionId,
        ///regions.CountryId,
        ///regions.IslandId,
        ///regions.Name,
        ///regions.`Description`,
        ///regions.DateCreated,
        ///regions.CreatedById,
        ///regions.LastModified
        ///FROM
        ///regions
        ///INNER JOIN countries ON regions.CountryId = countries.CountryId
        ///LEFT OUTER JOIN islands ON regions.IslandId = islands.IslandId.
        /// </summary>
        internal static string SqlGetAllRegions {
            get {
                return ResourceManager.GetString("SqlGetAllRegions", resourceCulture);
            }
        }
    }
}
