//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchKid.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChurchKid.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;applicationModuleGroups&gt;
        ///
        ///	&lt;applicationModuleGroup&gt;
        ///		&lt;name&gt;Administration&lt;/name&gt;	
        ///	&lt;/applicationModuleGroup&gt;
        ///
        ///	&lt;applicationModuleGroup&gt;
        ///		&lt;name&gt;General&lt;/name&gt;
        ///	&lt;/applicationModuleGroup&gt;
        ///	
        ///	&lt;applicationModuleGroup&gt;
        ///		&lt;name&gt;Geographical&lt;/name&gt;
        ///	&lt;/applicationModuleGroup&gt;
        ///
        ///	&lt;applicationModuleGroup&gt;
        ///		&lt;name&gt;Miscellaneous&lt;/name&gt;
        ///	&lt;/applicationModuleGroup&gt;
        ///
        ///	&lt;applicationModuleGroup&gt;
        ///		&lt;name&gt;Profiles&lt;/name&gt;
        ///	&lt;/applicationModuleGroup&gt;
        ///
        ///	&lt;applicationMod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplicationModuleGroups {
            get {
                return ResourceManager.GetString("ApplicationModuleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;applicationModules&gt;
        ///
        ///	&lt;applicationModule&gt;
        ///		&lt;group&gt;Administration&lt;/group&gt;
        ///		&lt;name&gt;System Users&lt;/name&gt;
        ///	&lt;/applicationModule&gt;
        ///	
        ///	&lt;applicationModule&gt;
        ///		&lt;group&gt;Administration&lt;/group&gt;
        ///		&lt;name&gt;Activity Logs&lt;/name&gt;
        ///	&lt;/applicationModule&gt;
        ///
        ///	&lt;applicationModule&gt;
        ///		&lt;group&gt;Geographical&lt;/group&gt;
        ///		&lt;name&gt;Countries&lt;/name&gt;
        ///	&lt;/applicationModule&gt;
        ///
        ///	&lt;applicationModule&gt;
        ///		&lt;group&gt;Geographical&lt;/group&gt;
        ///		&lt;name&gt;Islands&lt;/name&gt;
        ///	&lt;/applicationModule&gt;
        ///
        ///	&lt;applicationModule&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplicationModules {
            get {
                return ResourceManager.GetString("ApplicationModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;clusters&gt;
        ///
        ///	&lt;cluster&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;region&gt;NCR&lt;/region&gt;
        ///		&lt;group&gt;CAMANAVA&lt;/group&gt;
        ///		&lt;locality&gt;Malabon&lt;/locality&gt;
        ///		&lt;name&gt;Cluster 1&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/cluster&gt;
        ///
        ///	&lt;cluster&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;region&gt;NCR&lt;/region&gt;
        ///		&lt;group&gt;CAMANAVA&lt;/group&gt;
        ///		&lt;locality&gt;Caloocan&lt;/locality&gt;
        ///		&lt;name&gt;North Caloocan&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/cluster&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Clusters {
            get {
                return ResourceManager.GetString("Clusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;districts&gt;
        ///
        ///	&lt;district&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;region&gt;NCR&lt;/region&gt;
        ///		&lt;group&gt;CAMANAVA&lt;/group&gt;
        ///		&lt;locality&gt;Malabon&lt;/locality&gt;
        ///		&lt;cluster&gt;Cluster 1&lt;/cluster&gt;
        ///		&lt;name&gt;District 1&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;		
        ///	&lt;/district&gt;
        ///
        ///	&lt;district&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;region&gt;NCR&lt;/region&gt;
        ///		&lt;group&gt;CAMANAVA&lt;/group&gt;
        ///		&lt;locality&gt;Malabon&lt;/locality&gt;
        ///		&lt;cluster&gt;North Caloocan&lt;/cluster&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;educationalLevels&gt;
        ///
        ///	&lt;educationalLevel&gt;
        ///		&lt;name&gt;Nursery&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/educationalLevel&gt;
        ///
        ///	&lt;educationalLevel&gt;
        ///		&lt;name&gt;Preschool&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/educationalLevel&gt;
        ///
        ///	&lt;educationalLevel&gt;
        ///		&lt;name&gt;Kindergarten&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/educationalLevel&gt;
        ///
        ///	&lt;educationalLevel&gt;
        ///		&lt;name&gt;Elementary&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/educationalLevel&gt;
        ///
        ///	&lt;educationalLevel&gt;
        ///		&lt;name&gt;Highschoo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EducationalLevels {
            get {
                return ResourceManager.GetString("EducationalLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;islands&gt;
        ///
        ///	&lt;island&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;name&gt;Luzon&lt;/name&gt;
        ///	&lt;/island&gt;
        ///
        ///	&lt;island&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;name&gt;Visayas&lt;/name&gt;
        ///	&lt;/island&gt;
        ///
        ///	&lt;island&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;name&gt;Mindanao&lt;/name&gt;
        ///	&lt;/island&gt;
        ///	
        ///&lt;/islands&gt;
        ///.
        /// </summary>
        internal static string Islands {
            get {
                return ResourceManager.GetString("Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;localities&gt;
        ///
        ///	&lt;locality&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;region&gt;NCR&lt;/region&gt;
        ///		&lt;group&gt;CAMANAVA&lt;/group&gt;
        ///		&lt;name&gt;Malabon&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/locality&gt;
        ///
        ///	&lt;locality&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;region&gt;NCR&lt;/region&gt;
        ///		&lt;group&gt;CAMANAVA&lt;/group&gt;
        ///		&lt;name&gt;Caloocan&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/locality&gt;
        ///
        ///	&lt;locality&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Localities {
            get {
                return ResourceManager.GetString("Localities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;localityGroups&gt;
        ///
        ///	&lt;localityGroup&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;region&gt;NCR&lt;/region&gt;
        ///		&lt;name&gt;CAMANAVA&lt;/name&gt;
        ///		&lt;description&gt;Caloocan, Malabon, Navotas and Valenzuela&lt;/description&gt;	
        ///	&lt;/localityGroup&gt;
        ///	
        ///&lt;/localityGroups&gt;.
        /// </summary>
        internal static string LocalityGroups {
            get {
                return ResourceManager.GetString("LocalityGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;regions&gt;
        ///
        ///	&lt;region&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;name&gt;NCR&lt;/name&gt;
        ///		&lt;description&gt;National Capital Region&lt;/description&gt;
        ///	&lt;/region&gt;
        ///
        ///	&lt;region&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;name&gt;CAR&lt;/name&gt;
        ///		&lt;description&gt;Cordillera Administrative Region&lt;/description&gt;
        ///	&lt;/region&gt;
        ///
        ///	&lt;region&gt;
        ///		&lt;country&gt;Philippines&lt;/country&gt;
        ///		&lt;island&gt;Luzon&lt;/island&gt;
        ///		&lt;name&gt;Region I&lt;/name&gt;
        ///		&lt;description&gt;Ilocos Region&lt;/descr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;roles&gt;
        ///
        ///	&lt;role&gt;
        ///		&lt;name&gt;System Administrator&lt;/name&gt;
        ///		&lt;allowDelete&gt;0&lt;/allowDelete&gt;
        ///		&lt;administratorRole&gt;1&lt;/administratorRole&gt;
        ///	&lt;/role&gt;
        ///
        ///	&lt;role&gt;
        ///		&lt;name&gt;Training Administrator&lt;/name&gt;
        ///		&lt;allowDelete&gt;1&lt;/allowDelete&gt;
        ///		&lt;administratorRole&gt;0&lt;/administratorRole&gt;
        ///		&lt;privileges&gt;
        ///			&lt;privilege&gt;VIEWTRAININGCENTERS&lt;/privilege&gt;
        ///			&lt;privilege&gt;ADDTRAININGCENTERS&lt;/privilege&gt;
        ///			&lt;privilege&gt;EDITTRAININGCENTERS&lt;/privilege&gt;
        ///			&lt;privilege&gt;DELETETRAININGCENTERS&lt;/privilege [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;trainingLevels&gt;
        ///
        ///	&lt;trainingLevel&gt;
        ///		&lt;name&gt;FT - 1&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/trainingLevel&gt;
        ///
        ///	&lt;trainingLevel&gt;
        ///		&lt;name&gt;FT - 2&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/trainingLevel&gt;
        ///
        ///	&lt;trainingLevel&gt;
        ///		&lt;name&gt;FT - 3&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/trainingLevel&gt;
        ///
        ///	&lt;trainingLevel&gt;
        ///		&lt;name&gt;FT - 4&lt;/name&gt;
        ///		&lt;description&gt;&lt;/description&gt;
        ///	&lt;/trainingLevel&gt;
        ///
        ///	&lt;trainingLevel&gt;
        ///		&lt;name&gt;NZ&lt;/name&gt;
        ///		&lt;description&gt;Nazarite&lt;/description&gt;
        ///	&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TrainingLevels {
            get {
                return ResourceManager.GetString("TrainingLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;users&gt;
        ///
        ///	&lt;user&gt;
        ///		&lt;username&gt;churchkid&lt;/username&gt;
        ///		&lt;password&gt;C!0ud987&lt;/password&gt;
        ///		&lt;firstName&gt;Church&lt;/firstName&gt;
        ///		&lt;middleName&gt;&lt;/middleName&gt;
        ///		&lt;lastName&gt;Kid&lt;/lastName&gt;
        ///		&lt;nickName&gt;&lt;/nickName&gt;
        ///		&lt;email&gt;malabon.church.kid@gmail.com&lt;/email&gt;
        ///		&lt;roles&gt;
        ///			&lt;role&gt;System Administrator&lt;/role&gt;
        ///		&lt;/roles&gt;
        ///	&lt;/user&gt;
        ///
        ///	&lt;user&gt;
        ///		&lt;username&gt;trainingadmin&lt;/username&gt;
        ///		&lt;password&gt;Password987&lt;/password&gt;
        ///		&lt;firstName&gt;Training&lt;/firstName&gt;
        ///		&lt;middleName&gt;&lt;/middleName&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
