//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchKid.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChurchKid.Common.Resources.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Module Groups.
        /// </summary>
        public static string dataApplicationModuleGroups {
            get {
                return ResourceManager.GetString("dataApplicationModuleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Modules.
        /// </summary>
        public static string dataApplicationModules {
            get {
                return ResourceManager.GetString("dataApplicationModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string dataCountries {
            get {
                return ResourceManager.GetString("dataCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application User Roles.
        /// </summary>
        public static string dataRoles {
            get {
                return ResourceManager.GetString("dataRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Users.
        /// </summary>
        public static string dataUsers {
            get {
                return ResourceManager.GetString("dataUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available application module groups..
        /// </summary>
        public static string errNoModuleGroupsAvailable {
            get {
                return ResourceManager.GetString("errNoModuleGroupsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application user role has been specified into user: {0}..
        /// </summary>
        public static string errNoUserRoleSpecified {
            get {
                return ResourceManager.GetString("errNoUserRoleSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeded default {0} into the database..
        /// </summary>
        public static string msgSeededData {
            get {
                return ResourceManager.GetString("msgSeededData", resourceCulture);
            }
        }
    }
}
